# Generated by Django 3.2.7 on 2021-10-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='label',
            field=models.CharField(db_index=True, default='Unnamed', max_length=100),
        ),
    ]
